version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'kajyr'
    open-pull-requests-limit: 1
  - package-ecosystem: 'npm'
    directory: '/importer'
    schedule:
      interval: 'monthly'
    assignees:
      - 'kajyr'
  - package-ecosystem: 'npm'
    directory: '/templates'
    schedule:
      interval: 'monthly'
    assignees:
      - 'kajyr'
    open-pull-requests-limit: 1
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
    assignees:
      - 'kajyr'
